// <auto-generated />
using HoL.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HoL.Infrastructure.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20251209230415_raceBodyPartsRename")]
    partial class raceBodyPartsRename
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HoL.Domain.Entities.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseInitiative")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("BaseXP")
                        .HasColumnType("int");

                    b.Property<string>("Conviction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DomesticationValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("FightingSpiritNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Mobility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RaceCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RaceDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.PrimitiveCollection<string>("RaceHierarchySystem")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RaceHistory")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("RaceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StatsPrimar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vulnerabilities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZSM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Races", (string)null);
                });

            modelBuilder.Entity("HoL.Domain.Helpers.CurrencyGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency1Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Currency2Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Currency3Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Currency4Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Currency5Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Currencies", (string)null);
                });

            modelBuilder.Entity("HoL.Domain.Entities.Race", b =>
                {
                    b.OwnsOne("HoL.Domain.ValueObjects.Anatomi.BodyDimension", "BodyDimensins", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<int>("HeihtMax")
                                .HasColumnType("int");

                            b1.Property<int>("HeihtMin")
                                .HasColumnType("int");

                            b1.Property<int>("LengthMax")
                                .HasColumnType("int");

                            b1.Property<int>("LengthMin")
                                .HasColumnType("int");

                            b1.Property<int>("MaxAge")
                                .HasColumnType("int");

                            b1.Property<int>("RaceSize")
                                .HasColumnType("int");

                            b1.Property<int>("WeightMax")
                                .HasColumnType("int");

                            b1.Property<int>("WeightMin")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.ToTable("Races");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.OwnsMany("HoL.Domain.ValueObjects.Anatomi.BodyPart", "BodyParts", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Appearance")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<int>("Quantity")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(1);

                            b1.Property<string>("Function")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<bool>("IsMagical")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(false);

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("BodyPartCategory")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id", "Id");

                            b1.ToTable("RaceBodyParts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("Id");

                            b1.OwnsOne("HoL.Domain.Helpers.AnatomiHelpers.BodyPartAttack", "Attack", b2 =>
                                {
                                    b2.Property<int>("BodyPartRaceId")
                                        .HasColumnType("int");

                                    b2.Property<int>("BodyPartId")
                                        .HasColumnType("int");

                                    b2.Property<bool>("CanBeUsedWithOtherAttacks")
                                        .HasColumnType("bit");

                                    b2.Property<int>("DamageType")
                                        .HasColumnType("int");

                                    b2.Property<int>("Initiative")
                                        .HasColumnType("int");

                                    b2.HasKey("BodyPartRaceId", "BodyPartId");

                                    b2.ToTable("RaceBodyParts");

                                    b2.WithOwner()
                                        .HasForeignKey("BodyPartRaceId", "BodyPartId");

                                    b2.OwnsOne("HoL.Domain.Helpers.Dice", "DamageDice", b3 =>
                                        {
                                            b3.Property<int>("BodyPartAttackBodyPartRaceId")
                                                .HasColumnType("int");

                                            b3.Property<int>("BodyPartAttackBodyPartId")
                                                .HasColumnType("int");

                                            b3.Property<int>("Bonus")
                                                .HasColumnType("int");

                                            b3.Property<int>("Quantity")
                                                .HasColumnType("int");

                                            b3.Property<int>("Sides")
                                                .HasColumnType("int");

                                            b3.HasKey("BodyPartAttackBodyPartRaceId", "BodyPartAttackBodyPartId");

                                            b3.ToTable("RaceBodyParts");

                                            b3.WithOwner()
                                                .HasForeignKey("BodyPartAttackBodyPartRaceId", "BodyPartAttackBodyPartId");
                                        });

                                    b2.Navigation("DamageDice")
                                        .IsRequired();
                                });

                            b1.OwnsOne("HoL.Domain.Helpers.AnatomiHelpers.BodyPartDefense", "Defense", b2 =>
                                {
                                    b2.Property<int>("BodyPartRaceId")
                                        .HasColumnType("int");

                                    b2.Property<int>("BodyPartId")
                                        .HasColumnType("int");

                                    b2.Property<int>("ArmorValue")
                                        .HasColumnType("int");

                                    b2.Property<bool>("IsProtected")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("IsVital")
                                        .HasColumnType("bit");

                                    b2.HasKey("BodyPartRaceId", "BodyPartId");

                                    b2.ToTable("RaceBodyParts");

                                    b2.WithOwner()
                                        .HasForeignKey("BodyPartRaceId", "BodyPartId");
                                });

                            b1.Navigation("Attack");

                            b1.Navigation("Defense");
                        });

                    b.OwnsMany("HoL.Domain.ValueObjects.SpecialAbilities", "SpecialAbilities", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("AbilityDescription")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("AbilityName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id", "__synthesizedOrdinal");

                            b1.ToTable("Races");

                            b1.ToJson("SpecialAbilities");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.OwnsOne("HoL.Domain.ValueObjects.Treasure", "Treasure", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<int>("CurrencyAmountLevel1")
                                .HasColumnType("int");

                            b1.Property<int>("CurrencyAmountLevel2")
                                .HasColumnType("int");

                            b1.Property<int>("CurrencyAmountLevel3")
                                .HasColumnType("int");

                            b1.Property<int>("CurrencyAmountLevel4")
                                .HasColumnType("int");

                            b1.Property<int>("CurrencyAmountLevel5")
                                .HasColumnType("int");

                            b1.Property<int>("CurrencyGroupId")
                                .HasColumnType("int");

                            b1.Property<string>("GlobalCurrencyName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("CurrencyGroupId");

                            b1.ToTable("Races");

                            b1.HasOne("HoL.Domain.Helpers.CurrencyGroup", "CurrencyGroup")
                                .WithMany()
                                .HasForeignKey("CurrencyGroupId");

                            b1.WithOwner()
                                .HasForeignKey("Id");

                            b1.Navigation("CurrencyGroup");
                        });

                    b.Navigation("BodyDimensins")
                        .IsRequired();

                    b.Navigation("BodyParts");

                    b.Navigation("SpecialAbilities");

                    b.Navigation("Treasure");
                });
#pragma warning restore 612, 618
        }
    }
}
