// <auto-generated />
using HoL.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HoL.Infrastructure.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    partial class SqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CurrencyGroupSingleCurrency", b =>
                {
                    b.Property<int>("CurrencyGroupId")
                        .HasColumnType("int");

                    b.Property<int>("SingleCurrencyId")
                        .HasColumnType("int");

                    b.HasKey("CurrencyGroupId", "SingleCurrencyId");

                    b.HasIndex("SingleCurrencyId");

                    b.ToTable("CurrencyGroupSingleCurrency", (string)null);
                });

            modelBuilder.Entity("HoL.Infrastructure.Data.Models.CurrencyGroupDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("GroupName")
                        .IsUnique();

                    b.ToTable("CurrencyGroups", (string)null);
                });

            modelBuilder.Entity("HoL.Infrastructure.Data.Models.RaceDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseInitiative")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("BaseXP")
                        .HasColumnType("int");

                    b.Property<string>("Conviction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DomesticationValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("FightingSpiritNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("JsonBodyParts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bodyParts");

                    b.Property<string>("JsonBodyStats")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bodyStats");

                    b.Property<string>("JsonHierarchySystem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hierarchySystem");

                    b.Property<string>("JsonMobility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mobility");

                    b.Property<string>("JsonSpeciualAbilities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("speciualAbilities");

                    b.Property<string>("JsonVulnerabilities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vulnerabilities");

                    b.Property<string>("RaceCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RaceDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RaceHistory")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("RaceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ZSM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("RaceCategory");

                    b.HasIndex("RaceName")
                        .IsUnique();

                    b.ToTable("Races", (string)null);
                });

            modelBuilder.Entity("HoL.Infrastructure.Data.Models.SingleCurrencyDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExchangeRate")
                        .HasColumnType("int");

                    b.Property<int>("HierarchyLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShotName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("HierarchyLevel");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SingleCurrencies", (string)null);
                });

            modelBuilder.Entity("CurrencyGroupSingleCurrency", b =>
                {
                    b.HasOne("HoL.Infrastructure.Data.Models.CurrencyGroupDbModel", null)
                        .WithMany()
                        .HasForeignKey("CurrencyGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoL.Infrastructure.Data.Models.SingleCurrencyDbModel", null)
                        .WithMany()
                        .HasForeignKey("SingleCurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HoL.Infrastructure.Data.Models.RaceDbModel", b =>
                {
                    b.OwnsOne("HoL.Infrastructure.Data.Models.BodyDimensionDbModel", "BodyDimensins", b1 =>
                        {
                            b1.Property<int>("RaceDbModelId")
                                .HasColumnType("int");

                            b1.Property<int>("HeightMax")
                                .HasColumnType("int");

                            b1.Property<int>("HeightMin")
                                .HasColumnType("int");

                            b1.Property<int>("LengthMax")
                                .HasColumnType("int");

                            b1.Property<int>("LengthMin")
                                .HasColumnType("int");

                            b1.Property<int>("MaxAge")
                                .HasColumnType("int");

                            b1.Property<string>("RaceSize")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<int>("WeightMax")
                                .HasColumnType("int");

                            b1.Property<int>("WeightMin")
                                .HasColumnType("int");

                            b1.HasKey("RaceDbModelId");

                            b1.ToTable("Races");

                            b1.WithOwner()
                                .HasForeignKey("RaceDbModelId");
                        });

                    b.OwnsOne("HoL.Infrastructure.Data.Models.TreasureDbModel", "Treasure", b1 =>
                        {
                            b1.Property<int>("RaceDbModelId")
                                .HasColumnType("int");

                            b1.Property<string>("CoinQuantitiesJson")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("treasure_CoinQuantities");

                            b1.Property<int>("CurrencyGroup")
                                .HasColumnType("int")
                                .HasColumnName("treasure_CurrencyId");

                            b1.HasKey("RaceDbModelId");

                            b1.ToTable("Races");

                            b1.WithOwner()
                                .HasForeignKey("RaceDbModelId");
                        });

                    b.Navigation("BodyDimensins")
                        .IsRequired();

                    b.Navigation("Treasure");
                });
#pragma warning restore 612, 618
        }
    }
}
